import React, { createContext, useContext, useState, ReactNode } from 'react';

const translations = {
  en: {
    welcome: 'Welcome to ZeroTrace VPN',
    secure: 'Secure your internet connection with military-grade encryption.',
    vpnService: 'VPN Service',
    serviceDesc: 'Free VPN service with OpenVPN and PPTP protocols. No registration required.',
    freeVpn: 'Free VPN',
    protocolComparison: 'Protocol Comparison',
    feature: 'Feature',
    speed: 'Speed',
    security: 'Security',
    easeOfSetup: 'Ease of Setup',
    hardToBlock: 'Hard to Block',
    softwareRequired: 'Software Required',
    p2pTorrents: 'P2P/Torrents',
    good: 'Good',
    excellent: 'Excellent',
    moderate: 'Moderate',
    easy: 'Easy',
    yes: 'Yes',
    no: 'No',
    supported: 'Supported',
    supportTitle: 'Support VPNBook',
    supportDesc: 'This service is Advertisement and Donation based, if you enjoy this service, please consider donating so we can keep this as a free service and add more servers in the future.',
    donate: 'Donate Now',
    copyright: '© 2026 ZeroTraceVpn. All rights reserved. Located in India',
    dashboard: 'Dashboard',
    servers: 'Servers',
    configurations: 'Configurations',
    subscription: 'Subscription',
    adminPanel: 'Admin Panel',
    logout: 'Logout',
    // Admin Panel Translations
    adminConsole: 'Admin Console',
    users: 'Users',
    wireguard: 'WireGuard',
    openvpn: 'OpenVPN',
    alerts: 'Alerts',
    auditLog: 'Audit Log',
    settings: 'Settings',
    serverManagement: 'Server Management',
    sshControl: 'SSH control & real-time health',
    addServer: 'Add Server',
    userManagement: 'User Management',
    rolesQuotas: 'Roles, bandwidth quotas & session control',
    wireguardPeers: 'WireGuard Peers',
    generatePeers: 'Generate key pairs, QR codes & split-tunnel control',
    generatePeer: 'Generate Peer',
    openvpnCertificates: 'OpenVPN Certificates',
    issueCerts: 'Issue, revoke, download .ovpn configs',
    issueCert: 'Issue Cert',
    alertsNotifications: 'Alerts & Notifications',
    alertsDesc: 'Server downtime, cert expiry & bandwidth rules',
    newRule: 'New Rule',
    auditLogTitle: 'Audit Log',
    totalEvents: 'total events',
    systemSettings: 'System Settings',
    brandingSMTP: 'Branding, SMTP, network security & 2FA',
    realTimeOverview: 'Real-time infrastructure overview',
    // Common Admin Translations
    loading: 'Loading...',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    search: 'Search',
    filter: 'Filter',
    actions: 'Actions',
    status: 'Status',
    active: 'Active',
    inactive: 'Inactive',
    online: 'Online',
    offline: 'Offline',
    enabled: 'Enabled',
    disabled: 'Disabled',
    // Server Management
    country: 'Country',
    city: 'City',
    ipAddress: 'IP Address',
    protocol: 'Protocol',
    sshUser: 'SSH User',
    sshPort: 'SSH Port',
    activate: 'Activate',
    deactivate: 'Deactivate',
    noServersFound: 'No servers found. Add one above.',
    // User Management
    email: 'Email',
    role: 'Role',
    adminRole: 'Admin Role',
    plan: 'Plan',
    bandwidthLimit: 'BW Limit (MB)',
    twoFactorAuth: '2FA',
    subscriptionStatus: 'Sub Status',
    noUsersFound: 'No users found.',
    // WireGuard
    userId: 'User ID',
    assignedIp: 'Assigned IP',
    allowedIps: 'Allowed IPs',
    publicKey: 'Public Key',
    privateKey: 'Private Key',
    splitTunnel: 'Split Tunnel',
    fullTunnel: 'Full',
    lastHandshake: 'Last Handshake',
    generate: 'Generate',
    download: 'Download',
    showQrCode: 'Show QR Code',
    scanWithApp: 'Scan with WireGuard App',
    noPeersFound: 'No WireGuard peers. Generate one above.',
    // OpenVPN
    certName: 'Cert Name',
    commonName: 'Common Name',
    expiresAt: 'Expires At',
    expires: 'Expires',
    valid: 'Valid',
    revoked: 'Revoked',
    expired: 'Expired',
    revoke: 'Revoke',
    issue: 'Issue',
    noCertsFound: 'No certificates found.',
    // Alerts
    type: 'Type',
    target: 'Target',
    threshold: 'Threshold',
    lastFired: 'Last fired',
    noAlertsFound: 'No alert rules configured. Create one above.',
    // Audit Log
    time: 'Time',
    user: 'User',
    action: 'Action',
    severity: 'Severity',
    metadata: 'Metadata',
    allSeverities: 'All severities',
    noLogsFound: 'No logs found.',
    page: 'Page',
    of: 'of',
    globalNetworkNodes: 'Global Network Nodes',
    realTimeStatus: 'Real-time status and load balancing for available gateways.',
    systemsOperational: 'SYSTEMS OPERATIONAL',
    unableToConnect: 'Unable to connect to the API. Please ensure the backend is running.',
    ipAddress: 'IP Address',
    networkLoad: 'Network Load',
    selectLocation: 'Select Location',
    noActiveInfrastructure: 'No Active Infrastructure',
    onboardNode: 'Onboard a new node in the Admin Panel to begin.',
    systemAdmin: 'System Administration',
    infraControl: 'Infrastructure control and platform oversight.',
    totalUsers: 'Total Users',
    proSessions: 'Pro Sessions',
    totalNodes: 'Total Nodes',
    revenue: 'Revenue',
    networkNodeMgmt: 'Network Node Management',
    gatewayLocation: 'Gateway Location',
    publicIp: 'Public IP',
    healthStatus: 'Health Status',
    operation: 'Operation',
    provisioned: 'PROVISIONED',
    offline: 'OFFLINE',
    deactivate: 'Deactivate',
    activate: 'Activate',
    noServersFound: 'No servers found in database. Please onboard a node in Prisma Studio.',
    get_wireguard: 'Get WireGuard Client',
    get_openvpn: 'Get OpenVPN Client',
    download_config: 'Download Config',
    signup: 'Sign Up',
    signin: 'Sign In',
    name: 'Name',
    createAccount: 'Create Account',
    alreadyHaveAccount: 'Already have an account?',
    dontHaveAccount: "Don't have an account?",
    createOne: 'Create one',
    howItWorks: 'How It Works',
    setupGuide: 'Setup Guide',
    protocolComparison: 'Protocol Comparison',
    donate: 'Donate',
    copyright: '© 2026 ZeroTraceVPN. All rights reserved. Located in India.',
  },
  es: {
    welcome: 'Bienvenido a ZeroTrace VPN',
    secure: 'Asegura tu conexión a Internet con encriptación de grado militar.',
    vpnService: 'Servicio VPN',
    serviceDesc: 'Servicio VPN gratuito con protocolos OpenVPN y PPTP. No se requiere registro.',
    freeVpn: 'VPN Gratis',
    protocolComparison: 'Comparación de Protocolos',
    feature: 'Característica',
    speed: 'Velocidad',
    security: 'Seguridad',
    easeOfSetup: 'Facilidad de Configuración',
    hardToBlock: 'Difícil de Bloquear',
    softwareRequired: 'Software Requerido',
    p2pTorrents: 'P2P/Torrents',
    good: 'Bueno',
    excellent: 'Excelente',
    moderate: 'Moderado',
    easy: 'Fácil',
    yes: 'Sí',
    no: 'No',
    supported: 'Compatible',
    supportTitle: 'Apoya VPNBook',
    supportDesc: 'Este servicio se basa en anuncios y donaciones. Si disfrutas de este servicio, considera donar para que podamos mantenerlo como un servicio gratuito y agregar más servidores en el futuro.',
    donate: 'Donar Ahora',
    copyright: '© 2026 ZeroTraceVpn. Todos los derechos reservados. Ubicado en India',
    dashboard: 'Panel',
    servers: 'Servidores',
    configurations: 'Configuraciones',
    subscription: 'Suscripción',
    adminPanel: 'Panel de Admin',
    logout: 'Cerrar sesión',
    // Admin Panel Translations
    adminConsole: 'Consola de Admin',
    users: 'Usuarios',
    wireguard: 'WireGuard',
    openvpn: 'OpenVPN',
    alerts: 'Alertas',
    auditLog: 'Registro de Auditoría',
    settings: 'Configuración',
    serverManagement: 'Gestión de Servidores',
    sshControl: 'Control SSH y salud en tiempo real',
    addServer: 'Agregar Servidor',
    userManagement: 'Gestión de Usuarios',
    rolesQuotas: 'Roles, cuotas de ancho de banda y control de sesión',
    wireguardPeers: 'Pares WireGuard',
    generatePeers: 'Generar pares de claves, códigos QR y control de túnel dividido',
    generatePeer: 'Generar Par',
    openvpnCertificates: 'Certificados OpenVPN',
    issueCerts: 'Emitir, revocar, descargar configuraciones .ovpn',
    issueCert: 'Emitir Certificado',
    alertsNotifications: 'Alertas y Notificaciones',
    alertsDesc: 'Tiempo de inactividad del servidor, vencimiento de certificados y reglas de ancho de banda',
    newRule: 'Nueva Regla',
    auditLogTitle: 'Registro de Auditoría',
    totalEvents: 'eventos totales',
    systemSettings: 'Configuración del Sistema',
    brandingSMTP: 'Marca, SMTP, seguridad de red y 2FA',
    realTimeOverview: 'Descripción general de la infraestructura en tiempo real',
    // Common Admin Translations
    loading: 'Cargando...',
    save: 'Guardar',
    cancel: 'Cancelar',
    delete: 'Eliminar',
    edit: 'Editar',
    add: 'Agregar',
    search: 'Buscar',
    filter: 'Filtrar',
    actions: 'Acciones',
    status: 'Estado',
    active: 'Activo',
    inactive: 'Inactivo',
    online: 'En línea',
    offline: 'Desconectado',
    enabled: 'Habilitado',
    disabled: 'Deshabilitado',
    // Server Management
    country: 'País',
    city: 'Ciudad',
    ipAddress: 'Dirección IP',
    protocol: 'Protocolo',
    sshUser: 'Usuario SSH',
    sshPort: 'Puerto SSH',
    activate: 'Activar',
    deactivate: 'Desactivar',
    noServersFound: 'No se encontraron servidores. Agregue uno arriba.',
    // User Management
    email: 'Correo electrónico',
    role: 'Rol',
    adminRole: 'Rol de administrador',
    plan: 'Plan',
    bandwidthLimit: 'Límite de ancho de banda (MB)',
    twoFactorAuth: '2FA',
    subscriptionStatus: 'Estado de suscripción',
    noUsersFound: 'No se encontraron usuarios.',
    // WireGuard
    userId: 'ID de usuario',
    assignedIp: 'IP asignada',
    allowedIps: 'IPs permitidas',
    publicKey: 'Clave pública',
    privateKey: 'Clave privada',
    splitTunnel: 'Túnel dividido',
    fullTunnel: 'Completo',
    lastHandshake: 'Último handshake',
    generate: 'Generar',
    download: 'Descargar',
    showQrCode: 'Mostrar código QR',
    scanWithApp: 'Escanear con la aplicación WireGuard',
    noPeersFound: 'No hay pares WireGuard. Genere uno arriba.',
    // OpenVPN
    certName: 'Nombre del certificado',
    commonName: 'Nombre común',
    expiresAt: 'Expira en',
    expires: 'Expira',
    valid: 'Válido',
    revoked: 'Revocado',
    expired: 'Expirado',
    revoke: 'Revocar',
    issue: 'Emitir',
    noCertsFound: 'No se encontraron certificados.',
    // Alerts
    type: 'Tipo',
    target: 'Objetivo',
    threshold: 'Umbral',
    lastFired: 'Último activado',
    noAlertsFound: 'No hay reglas de alerta configuradas. Cree una arriba.',
    // Audit Log
    time: 'Hora',
    user: 'Usuario',
    action: 'Acción',
    severity: 'Gravedad',
    metadata: 'Metadatos',
    allSeverities: 'Todas las gravedades',
    noLogsFound: 'No se encontraron registros.',
    page: 'Página',
    of: 'de',
    globalNetworkNodes: 'Nodos de Red Globales',
    realTimeStatus: 'Estado en tiempo real y equilibrio de carga.',
    systemsOperational: 'SISTEMAS OPERATIVOS',
    unableToConnect: 'No se puede conectar a la API.',
    ipAddress: 'Dirección IP',
    networkLoad: 'Carga de red',
    selectLocation: 'Seleccionar ubicación',
    noActiveInfrastructure: 'Sin infraestructura activa',
    onboardNode: 'Agregue un nuevo nodo en el Panel de Admin para comenzar.',
    systemAdmin: 'Administración del Sistema',
    infraControl: 'Control de infraestructura y supervisión.',
    totalUsers: 'Usuarios Totales',
    proSessions: 'Sesiones Pro',
    totalNodes: 'Nodos Totales',
    revenue: 'Ingresos',
    networkNodeMgmt: 'Gestión de Nodos de Red',
    gatewayLocation: 'Ubicación de Puerta de Enlace',
    publicIp: 'IP Pública',
    healthStatus: 'Estado de Salud',
    operation: 'Operación',
    provisioned: 'PROVISIONADO',
    offline: 'DESCONECTADO',
    deactivate: 'Desactivar',
    activate: 'Activar',
    noServersFound: 'No se encontraron servidores.',
    get_wireguard: 'Obtener cliente WireGuard',
    get_openvpn: 'Obtener cliente OpenVPN',
    download_config: 'Descargar configuración',
    signup: 'Registrarse',
    signin: 'Iniciar sesión',
    name: 'Nombre',
    createAccount: 'Crear cuenta',
    alreadyHaveAccount: '¿Ya tienes una cuenta?',
    dontHaveAccount: '¿No tienes una cuenta?',
    createOne: 'Crear una',
    howItWorks: 'Cómo Funciona',
    setupGuide: 'Guía de Configuración',
    protocolComparison: 'Comparación de Protocolos',
    donate: 'Donar Ahora',
    copyright: '© 2026 ZeroTraceVPN. Todos los derechos reservados. Ubicado en India.',
  },
  fr: {
    welcome: 'Bienvenue sur ZeroTrace VPN',
    secure: 'Sécurisez votre connexion Internet avec un chiffrement de niveau militaire.',
    vpnService: 'Service VPN',
    serviceDesc: 'Service VPN gratuit avec protocoles OpenVPN et PPTP. Aucune inscription requise.',
    freeVpn: 'VPN Gratuit',
    protocolComparison: 'Comparaison des Protocoles',
    feature: 'Fonctionnalité',
    speed: 'Vitesse',
    security: 'Sécurité',
    easeOfSetup: 'Facilité de Configuration',
    hardToBlock: 'Difficile à Bloquer',
    softwareRequired: 'Logiciel Requis',
    p2pTorrents: 'P2P/Torrents',
    good: 'Bon',
    excellent: 'Excellent',
    moderate: 'Modéré',
    easy: 'Facile',
    yes: 'Oui',
    no: 'Non',
    supported: 'Supporté',
    supportTitle: 'Soutenir VPNBook',
    supportDesc: 'Ce service est basé sur les publicités et les dons. Si vous aimez ce service, veuillez envisager de faire un don pour que nous puissions le maintenir comme un service gratuit et ajouter plus de serveurs à l\'avenir.',
    donate: 'Faire un don',
    copyright: '© 2026 ZeroTraceVpn. Tous droits réservés. Situé en Inde',
    dashboard: 'Tableau de bord',
    servers: 'Serveurs',
    configurations: 'Configurations',
    subscription: 'Abonnement',
    adminPanel: 'Panneau d\'administration',
    logout: 'Déconnexion',
    // Admin Panel Translations
    adminConsole: 'Console d\'administration',
    users: 'Utilisateurs',
    wireguard: 'WireGuard',
    openvpn: 'OpenVPN',
    alerts: 'Alertes',
    auditLog: 'Journal d\'audit',
    settings: 'Paramètres',
    serverManagement: 'Gestion des serveurs',
    sshControl: 'Contrôle SSH et santé en temps réel',
    addServer: 'Ajouter un serveur',
    userManagement: 'Gestion des utilisateurs',
    rolesQuotas: 'Rôles, quotas de bande passante et contrôle de session',
    wireguardPeers: 'Pairs WireGuard',
    generatePeers: 'Générer des paires de clés, des codes QR et un contrôle de tunnel divisé',
    generatePeer: 'Générer un pair',
    openvpnCertificates: 'Certificats OpenVPN',
    issueCerts: 'Émettre, révoquer, télécharger des configurations .ovpn',
    issueCert: 'Émettre un certificat',
    alertsNotifications: 'Alertes et notifications',
    alertsDesc: 'Temps d\'arrêt du serveur, expiration du certificat et règles de bande passante',
    newRule: 'Nouvelle règle',
    auditLogTitle: 'Journal d\'audit',
    totalEvents: 'événements totaux',
    systemSettings: 'Paramètres système',
    brandingSMTP: 'Image de marque, SMTP, sécurité réseau et 2FA',
    realTimeOverview: 'Aperçu de l\'infrastructure en temps réel',
    globalNetworkNodes: 'Nœuds de Réseau Mondiaux',
    realTimeStatus: 'Statut en temps réel et équilibrage de charge.',
    systemsOperational: 'SYSTÈMES OPÉRATIONNELS',
    unableToConnect: 'Impossible de se connecter à l\'API.',
    ipAddress: 'Adresse IP',
    networkLoad: 'Charge réseau',
    selectLocation: 'Sélectionner l\'emplacement',
    noActiveInfrastructure: 'Aucune infrastructure active',
    onboardNode: 'Ajoutez un nouveau nœud dans le Panneau d\'administration pour commencer.',
    systemAdmin: 'Administration du Système',
    infraControl: 'Contrôle de l\'infrastructure et supervision.',
    totalUsers: 'Utilisateurs Totaux',
    proSessions: 'Sessions Pro',
    totalNodes: 'Nœuds Totaux',
    revenue: 'Revenus',
    networkNodeMgmt: 'Gestion des Nœuds de Réseau',
    gatewayLocation: 'Emplacement de la passerelle',
    publicIp: 'IP Publique',
    healthStatus: 'État de santé',
    operation: 'Opération',
    provisioned: 'APPROVISIONNÉ',
    offline: 'HORS LIGNE',
    deactivate: 'Désactiver',
    activate: 'Activar',
    noServersFound: 'Aucun serveur trouvé.',
    get_wireguard: 'Obtenir le client WireGuard',
    get_openvpn: 'Obtenir le client OpenVPN',
    download_config: 'Télécharger la configuration',
    signup: 'S\'inscrire',
    signin: 'Se connecter',
    name: 'Nom',
    createAccount: 'Créer un compte',
    alreadyHaveAccount: 'Vous avez déjà un compte?',
    dontHaveAccount: 'Vous n\'avez pas de compte?',
    createOne: 'En créer un',
    howItWorks: 'Comment ça marche',
    setupGuide: 'Guide de Configuration',
    protocolComparison: 'Comparaison des Protocoles',
    donate: 'Faire un don',
    copyright: '© 2026 ZeroTraceVPN. Tous droits réservés. Situé en Inde.',
  },
  de: {
    welcome: 'Willkommen bei ZeroTrace VPN',
    secure: 'Sichern Sie Ihre Internetverbindung mit militärischer Verschlüsselung.',
    vpnService: 'VPN-Dienst',
    serviceDesc: 'Kostenloser VPN-Dienst mit OpenVPN- und PPTP-Protokollen. Keine Registrierung erforderlich.',
    freeVpn: 'Kostenloses VPN',
    protocolComparison: 'Protokollvergleich',
    feature: 'Merkmal',
    speed: 'Geschwindigkeit',
    security: 'Sicherheit',
    easeOfSetup: 'Benutzerfreundlichkeit',
    hardToBlock: 'Schwer zu Blockieren',
    softwareRequired: 'Erforderliche Software',
    p2pTorrents: 'P2P/Torrents',
    good: 'Gut',
    excellent: 'Ausgezeichnet',
    moderate: 'Moderat',
    easy: 'Einfach',
    yes: 'Ja',
    no: 'Nein',
    supported: 'Unterstützt',
    supportTitle: 'Unterstützen Sie VPNBook',
    supportDesc: 'Dieser Service basiert auf Werbung und Spenden. Wenn Ihnen dieser Service gefällt, erwägen Sie bitte eine Spende, damit wir ihn kostenlos halten und in Zukunft mehr Server hinzufügen können.',
    donate: 'Jetzt spenden',
    copyright: '© 2026 ZeroTraceVpn. Alle Rechte vorbehalten. Standort: Indien',
    dashboard: 'Dashboard',
    servers: 'Server',
    configurations: 'Konfigurationen',
    subscription: 'Abonnement',
    adminPanel: 'Admin-Bereich',
    logout: 'Abmelden',
    // Admin Panel Translations
    adminConsole: 'Admin-Konsole',
    users: 'Benutzer',
    wireguard: 'WireGuard',
    openvpn: 'OpenVPN',
    alerts: 'Warnungen',
    auditLog: 'Prüfprotokoll',
    settings: 'Einstellungen',
    serverManagement: 'Serververwaltung',
    sshControl: 'SSH-Steuerung und Echtzeit-Gesundheit',
    addServer: 'Server hinzufügen',
    userManagement: 'Benutzerverwaltung',
    rolesQuotas: 'Rollen, Bandbreitenkontingente und Sitzungssteuerung',
    wireguardPeers: 'WireGuard-Peers',
    generatePeers: 'Schlüsselpaare, QR-Codes und Split-Tunnel-Steuerung generieren',
    generatePeer: 'Peer generieren',
    openvpnCertificates: 'OpenVPN-Zertifikate',
    issueCerts: 'Ausstellen, widerrufen, .ovpn-Konfigurationen herunterladen',
    issueCert: 'Zertifikat ausstellen',
    alertsNotifications: 'Warnungen und Benachrichtigungen',
    alertsDesc: 'Server-Ausfallzeit, Zertifikatsablauf und Bandbreitenregeln',
    newRule: 'Neue Regel',
    auditLogTitle: 'Prüfprotokoll',
    totalEvents: 'Ereignisse insgesamt',
    systemSettings: 'Systemeinstellungen',
    brandingSMTP: 'Branding, SMTP, Netzwerksicherheit und 2FA',
    realTimeOverview: 'Echtzeit-Infrastrukturübersicht',
    globalNetworkNodes: 'Globale Netzwerkknoten',
    realTimeStatus: 'Echtzeitstatus und Lastausgleich.',
    systemsOperational: 'SYSTEME BETRIEBSBEREIT',
    unableToConnect: 'Verbindung zur API fehlgeschlagen.',
    ipAddress: 'IP-Adresse',
    networkLoad: 'Netzwerklast',
    selectLocation: 'Standort auswählen',
    noActiveInfrastructure: 'Keine aktive Infrastruktur',
    onboardNode: 'Fügen Sie im Admin-Bereich einen neuen Knoten hinzu, um zu beginnen.',
    systemAdmin: 'Systemverwaltung',
    infraControl: 'Infrastrukturkontrolle und Plattformübersicht.',
    totalUsers: 'Benutzer gesamt',
    proSessions: 'Pro-Sitzungen',
    totalNodes: 'Knoten gesamt',
    revenue: 'Einnahmen',
    networkNodeMgmt: 'Netzwerkknoten-Management',
    gatewayLocation: 'Gateway-Standort',
    publicIp: 'Öffentliche IP',
    healthStatus: 'Gesundheitsstatus',
    operation: 'Betrieb',
    provisioned: 'BEREITGESTELLT',
    offline: 'OFFLINE',
    deactivate: 'Deaktivieren',
    activate: 'Aktivieren',
    noServersFound: 'Keine Server gefunden.',
    get_wireguard: 'WireGuard-Client herunterladen',
    get_openvpn: 'OpenVPN-Client herunterladen',
    download_config: 'Konfiguration herunterladen',
    signup: 'Registrieren',
    signin: 'Anmelden',
    name: 'Name',
    createAccount: 'Konto erstellen',
    alreadyHaveAccount: 'Haben Sie bereits ein Konto?',
    dontHaveAccount: 'Haben Sie kein Konto?',
    createOne: 'Erstellen Sie eines',
    howItWorks: 'So funktioniert es',
    setupGuide: 'Einrichtungsanleitung',
    protocolComparison: 'Protokollvergleich',
    donate: 'Jetzt spenden',
    copyright: '© 2026 ZeroTraceVPN. Alle Rechte vorbehalten. Standort: Indien.',
  },
  zh: {
    welcome: '欢迎来到 ZeroTrace VPN',
    secure: '使用军事级加密保护您的互联网连接。',
    vpnService: 'VPN 服务',
    serviceDesc: '免费 VPN 服务，支持 OpenVPN 和 PPTP 协议。无需注册。',
    freeVpn: '免费 VPN',
    protocolComparison: '协议对比',
    feature: '功能',
    speed: '速度',
    security: '安全性',
    easeOfSetup: '设置简便性',
    hardToBlock: '难以阻止',
    softwareRequired: '所需软件',
    p2pTorrents: 'P2P/种子',
    good: '良好',
    excellent: '优秀',
    moderate: '中等',
    easy: '简单',
    yes: '是',
    no: '否',
    supported: '支持',
    supportTitle: '支持 VPNBook',
    supportDesc: '本服务基于广告和捐赠。如果您喜欢本服务，请考虑捐赠，以便我们能够将其保持为免费服务并在未来添加更多服务器。',
    donate: '现在捐赠',
    copyright: '© 2026 ZeroTraceVpn。版权所有。位于印度',
    dashboard: '仪表板',
    servers: '服务器',
    configurations: '配置',
    subscription: '订阅',
    adminPanel: '管理面板',
    logout: '登出',
    // Admin Panel Translations
    adminConsole: '管理控制台',
    users: '用户',
    wireguard: 'WireGuard',
    openvpn: 'OpenVPN',
    alerts: '警报',
    auditLog: '审计日志',
    settings: '设置',
    serverManagement: '服务器管理',
    sshControl: 'SSH控制和实时健康',
    addServer: '添加服务器',
    userManagement: '用户管理',
    rolesQuotas: '角色、带宽配额和会话控制',
    wireguardPeers: 'WireGuard对等端',
    generatePeers: '生成密钥对、二维码和分隔隧道控制',
    generatePeer: '生成对等端',
    openvpnCertificates: 'OpenVPN证书',
    issueCerts: '颁发、撤销、下载.ovpn配置',
    issueCert: '颁发证书',
    alertsNotifications: '警报和通知',
    alertsDesc: '服务器停机时间、证书过期和带宽规则',
    newRule: '新规则',
    auditLogTitle: '审计日志',
    totalEvents: '总事件',
    systemSettings: '系统设置',
    brandingSMTP: '品牌、SMTP、网络安全和2FA',
    realTimeOverview: '实时基础设施概览',
    globalNetworkNodes: '全球网络节点',
    realTimeStatus: '可用网关的实时状态和负载均衡。',
    systemsOperational: '系统运行正常',
    unableToConnect: '无法连接到API。',
    ipAddress: 'IP地址',
    networkLoad: '网络负载',
    selectLocation: '选择位置',
    noActiveInfrastructure: '没有活跃的基础设施',
    onboardNode: '在管理面板中载入新节点以开始。',
    systemAdmin: '系统管理',
    infraControl: '基础设施控制和平台监督。',
    totalUsers: '总用户',
    proSessions: '高级会话',
    totalNodes: '总节点',
    revenue: '收入',
    networkNodeMgmt: '网络节点管理',
    gatewayLocation: '网关位置',
    publicIp: '公共IP',
    healthStatus: '健康状态',
    operation: '操作',
    provisioned: '已配置',
    offline: '离线',
    deactivate: '停用',
    activate: '激活',
    noServersFound: '未找到服务器。',
    get_wireguard: '获取 WireGuard 客户端',
    get_openvpn: '获取 OpenVPN 客户端',
    download_config: '下载配置',
    signup: '注册',
    signin: '登录',
    name: '姓名',
    createAccount: '创建账户',
    alreadyHaveAccount: '已有账户？',
    dontHaveAccount: '没有账户？',
    createOne: '创建一个',
    howItWorks: '工作原理',
    setupGuide: '设置指南',
    protocolComparison: '协议对比',
    donate: '现在捐赠',
    copyright: '© 2026 ZeroTraceVPN。版权所有。位于印度。',
  },
  hi: {
    welcome: 'ZeroTrace VPN में आपका स्वागत है',
    secure: 'सैन्य-ग्रेड एन्क्रिप्शन के साथ अपने इंटरनेट कनेक्शन को सुरक्षित करें।',
    vpnService: 'VPN सेवा',
    serviceDesc: 'OpenVPN और PPTP प्रोटोकॉल के साथ निःशुल्क VPN सेवा। कोई पंजीकरण आवश्यक नहीं।',
    freeVpn: 'निःशुल्क VPN',
    protocolComparison: 'प्रोटोकॉल तुलना',
    feature: 'विशेषता',
    speed: 'गति',
    security: 'सुरक्षा',
    easeOfSetup: 'सेटअप में आसानी',
    hardToBlock: 'अवरुद्ध करना कठिन',
    softwareRequired: 'आवश्यक सॉफ्टवेयर',
    p2pTorrents: 'P2P/टोरेंट',
    good: 'अच्छा',
    excellent: 'उत्कृष्ट',
    moderate: 'मध्यम',
    easy: 'आसान',
    yes: 'हाँ',
    no: 'नहीं',
    supported: 'समर्थित',
    supportTitle: 'VPNBook का समर्थन करें',
    supportDesc: 'यह सेवा विज्ञापन और दान पर आधारित है। यदि आप इस सेवा का आनंद लेते हैं, तो कृपया दान करने पर विचार करें ताकि हम इसे एक निःशुल्क सेवा के रूप में रख सकें और भविष्य में अधिक सर्वर जोड़ सकें।',
    donate: 'अभी दान करें',
    copyright: '© 2026 ZeroTraceVpn। सर्वाधिकार सुरक्षित। भारत में स्थित',
    dashboard: 'डैशबोर्ड',
    servers: 'सर्वर',
    configurations: 'कॉन्फ़िगरेशन',
    subscription: 'सदस्यता',
    adminPanel: 'व्यवस्थापक पैनल',
    logout: 'लॉग आउट',
    // Admin Panel Translations
    adminConsole: 'व्यवस्थापक कंसोल',
    users: 'उपयोगकर्ता',
    wireguard: 'WireGuard',
    openvpn: 'OpenVPN',
    alerts: 'चेतावनी',
    auditLog: 'ऑडिट लॉग',
    settings: 'सेटिंग्स',
    serverManagement: 'सर्वर प्रबंधन',
    sshControl: 'SSH नियंत्रण और वास्तविक समय स्वास्थ्य',
    addServer: 'सर्वर जोड़ें',
    userManagement: 'उपयोगकर्ता प्रबंधन',
    rolesQuotas: 'भूमिकाएं, बैंडविड्थ कोटा और सत्र नियंत्रण',
    wireguardPeers: 'WireGuard पीयर्स',
    generatePeers: 'कुंजी जोड़े, QR कोड और स्प्लिट-टनल नियंत्रण उत्पन्न करें',
    generatePeer: 'पीयर उत्पन्न करें',
    openvpnCertificates: 'OpenVPN प्रमाणपत्र',
    issueCerts: 'जारी करें, रद्द करें, .ovpn कॉन्फ़िग डाउनलोड करें',
    issueCert: 'प्रमाणपत्र जारी करें',
    alertsNotifications: 'चेतावनियां और सूचनाएं',
    alertsDesc: 'सर्वर डाउनटाइम, प्रमाणपत्र समाप्ति और बैंडविड्थ नियम',
    newRule: 'नया नियम',
    auditLogTitle: 'ऑडिट लॉग',
    totalEvents: 'कुल घटनाएं',
    systemSettings: 'सिस्टम सेटिंग्स',
    brandingSMTP: 'ब्रांडिंग, SMTP, नेटवर्क सुरक्षा और 2FA',
    realTimeOverview: 'वास्तविक समय बुनियादी ढांचा अवलोकन',
    globalNetworkNodes: 'वैश्विक नेटवर्क नोड्स',
    realTimeStatus: 'उपलब्ध गेटवे के लिए वास्तविक समय की स्थिति और लोड संतुलन।',
    systemsOperational: 'सिस्टम चालू है',
    unableToConnect: 'एपीआई से कनेक्ट करने में असमर्थ।',
    ipAddress: 'आईपी पता',
    networkLoad: 'नेटवर्क लोड',
    selectLocation: 'स्थान चुनें',
    noActiveInfrastructure: 'कोई सक्रिय बुनियादी ढांचा नहीं',
    onboardNode: 'शुरू करने के लिए व्यवस्थापक पैनल में एक नया नोड ऑनबोर्ड करें।',
    systemAdmin: 'सिस्टम प्रशासन',
    infraControl: 'बुनियादी ढांचा नियंत्रण और मंच की देखरेख।',
    totalUsers: 'कुल उपयोगकर्ता',
    proSessions: 'प्रो सत्र',
    totalNodes: 'कुल नोड्स',
    revenue: 'राजस्व',
    networkNodeMgmt: 'नेटवर्क नोड प्रबंधन',
    gatewayLocation: 'गेटवे स्थान',
    publicIp: 'सार्वजनिक आईपी',
    healthStatus: 'स्वास्थ्य की स्थिति',
    operation: 'ऑपरेशन',
    provisioned: 'प्रावधानित',
    offline: 'ऑफ़लाइन',
    deactivate: 'निष्क्रिय करें',
    activate: 'सक्रिय करें',
    noServersFound: 'कोई सर्वर नहीं मिला।',
    get_wireguard: 'WireGuard क्लाइंट प्राप्त करें',
    get_openvpn: 'OpenVPN क्लाइंट प्राप्त करें',
    download_config: 'कॉन्फ़िग डाउनलोड करें',
    signup: 'साइन अप',
    signin: 'साइन इन',
    name: 'नाम',
    createAccount: 'खाता बनाएं',
    alreadyHaveAccount: 'पहले से खाता है?',
    dontHaveAccount: 'खाता नहीं है?',
    createOne: 'बनाएं',
    howItWorks: 'यह कैसे काम करता है',
    setupGuide: 'सेटअप गाइड',
    protocolComparison: 'प्रोटोकॉल तुलना',
    donate: 'अभी दान करें',
    copyright: '© 2026 ZeroTraceVPN। सर्वाधिकार सुरक्षित। भारत में स्थित।',
  }
};

type Language = keyof typeof translations;

interface LanguageContextType {
  selectedLanguage: Language;
  setSelectedLanguage: (lang: Language) => void;
  t: typeof translations.en;
  languages: { code: string; name: string }[];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [selectedLanguage, setSelectedLanguage] = useState<Language>('en');

  const languages = [
    { code: 'en', name: 'English' },
    { code: 'es', name: 'Español' },
    { code: 'fr', name: 'Français' },
    { code: 'de', name: 'Deutsch' },
    { code: 'zh', name: '中文' },
    { code: 'hi', name: 'हिन्दी' }
  ];

  const t = translations[selectedLanguage];

  return (
    <LanguageContext.Provider value={{ selectedLanguage, setSelectedLanguage, t, languages }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
